name: run-matrix

on:
  push
defaults:
  run:
    shell: nu {0}

jobs:
  test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ver: [0.60.0, 0.61.0]

    runs-on: ${{ matrix.os }}
    name: test (${{matrix.os}}, nu@${{matrix.ver}})
    steps:
    - uses: actions/checkout@v3
    - name: Setup nu@${{matrix.ver}}
      uses: hustcer/setup-nu@main
      with:
        version: ${{matrix.ver}}
      env:
        ACTIONS_STEP_DEBUG: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: $'Nu version info:(char nl)'; version
    - run: $'Current env:(char nl)'; $env
    - run: $'Nu path:(which nu)(char nl)'
    - run: $"(char nl)Dir contents:(char nl)"; ls ((which nu).path.0 | path dirname)
