name: run-matrix

on:
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: nu {0}

jobs:
  test-matrix:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        ver: [0.67, 0.66.2, 0.65, 0.64, 0.63, 0.62, 0.61, 0.60.0]

    runs-on: ${{ matrix.os }}
    name: test (${{matrix.os}}, nu@${{matrix.ver}})
    steps:
    - uses: actions/checkout@v3
    - name: Setup nu@${{matrix.ver}}
      uses: hustcer/setup-nu@v2
      with:
        version: ${{matrix.ver}}
      env:
        ACTIONS_STEP_DEBUG: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: $'Nu version info:(char nl)'; version
    - run: $'Current env:(char nl)'; $env
    - run: $'Nu path:(which nu)(char nl)'
    - run: $"(char nl)Dir contents:(char nl)"; ls ((which nu).path.0 | path dirname)
